version: '3.8'

services:
  api:
    build: .
    container_name: car_dealership
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=development
      - PORT=3000
      - SERVICE_NAME=Assessment
      - MONGO_URI=mongodb://root:example@mongodb:27017
      - AUTH_JWT_SECRET=tEST%"728829200JFNDKFDK"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  mongodb:
    image: mongo:latest
    container_name: car_dealership_db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongo-data:/data/mongodata

volumes:
  mongo-data:
